baseURL = "https://jueng9595.github.io/firstproject/"
languageCode = "ko-kr"
title = "Security Study Log"
theme = "PaperMod"

# 하위 경로(/firstproject/)가 있을 때 가장 확실한 조합입니다
canonifyURLs = false
relativeURLs = true