baseURL = "https://jueng9595.github.io/firstproject/"
languageCode = "ko-kr"
title = "Security Study Log"
theme = "PaperMod"

# 이 두 설정이 경로 문제를 강제로 해결합니다
canonifyURLs = true
relativeURLs = false  # 하위 경로가 있을 땐 false가 더 안정적입니다

[params.profileMode]
    enabled = true
    title = "장양환"
    subtitle = "Cyber Security Learner"
    imageUrl = "https://github.com/jueng9595.png"
    imageWidth = 150
    imageHeight = 150